
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author cesar
 */
public class Ventana extends javax.swing.JFrame {

    Grafo grafo = new Grafo();
    
    public Ventana() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setResizable(false);
        this.setTitle("U4. Práctica 1. Aplicación sobre GRAFOS");
        this.jButtonMatrizAdyacencia.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextFieldVertice = new javax.swing.JTextField();
        jButtonInsertarVertice = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jButtonEliminarVertice = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jTextFieldOrigen = new javax.swing.JTextField();
        jButtonInsertarArista = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jTextFieldDestino = new javax.swing.JTextField();
        jButtonEliminarArista = new javax.swing.JButton();
        jButtonMatrizAdyacencia = new javax.swing.JButton();
        jButtonListaAdyacencia = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jButtonVerificarCamino = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jTextFieldPATH = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea2 = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButtonInsertarVertice.setText("INSERTAR VERTICE");
        jButtonInsertarVertice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonInsertarVerticeActionPerformed(evt);
            }
        });

        jLabel1.setText("VERTICE:");

        jButtonEliminarVertice.setText("ELIMINAR VERTICE");
        jButtonEliminarVertice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEliminarVerticeActionPerformed(evt);
            }
        });

        jLabel2.setText("ORIGEN:");

        jButtonInsertarArista.setText("INSERTAR ARISTA");
        jButtonInsertarArista.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonInsertarAristaActionPerformed(evt);
            }
        });

        jLabel3.setText("DESTINO:");

        jButtonEliminarArista.setText("ELIMINAR ARISTA");
        jButtonEliminarArista.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEliminarAristaActionPerformed(evt);
            }
        });

        jButtonMatrizAdyacencia.setText("MATRIZ ADYACENCIA");
        jButtonMatrizAdyacencia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonMatrizAdyacenciaActionPerformed(evt);
            }
        });

        jButtonListaAdyacencia.setText("LISTA ADYACENCIA");
        jButtonListaAdyacencia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonListaAdyacenciaActionPerformed(evt);
            }
        });

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane2.setViewportView(jTextArea1);

        jButtonVerificarCamino.setText("VERIFICAR CAMINO");
        jButtonVerificarCamino.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonVerificarCaminoActionPerformed(evt);
            }
        });

        jLabel4.setText("PATH:");

        jTextArea2.setEditable(false);
        jTextArea2.setColumns(20);
        jTextArea2.setRows(5);
        jTextArea2.setText("NOTA: PARA LA LISTA DE\nADYACENCIA UTILIZAR\nEL TEXT FIELD DE VERTICE,\nESCRIBIR EL VERTICE.");
        jScrollPane1.setViewportView(jTextArea2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButtonMatrizAdyacencia)
                            .addComponent(jButtonListaAdyacencia, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane2))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 65, Short.MAX_VALUE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(jTextFieldOrigen, javax.swing.GroupLayout.DEFAULT_SIZE, 69, Short.MAX_VALUE)
                                            .addComponent(jTextFieldVertice))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(jButtonInsertarVertice, javax.swing.GroupLayout.DEFAULT_SIZE, 135, Short.MAX_VALUE)
                                            .addComponent(jButtonInsertarArista, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jTextFieldDestino, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jButtonEliminarArista, javax.swing.GroupLayout.DEFAULT_SIZE, 135, Short.MAX_VALUE))))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(jTextFieldPATH, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jButtonVerificarCamino, javax.swing.GroupLayout.DEFAULT_SIZE, 135, Short.MAX_VALUE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jButtonEliminarVertice))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldVertice, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonInsertarVertice, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonEliminarVertice, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldOrigen, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonInsertarArista, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextFieldDestino, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonEliminarArista, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextFieldPATH, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonVerificarCamino, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(jButtonMatrizAdyacencia, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButtonListaAdyacencia, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(13, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonInsertarVerticeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonInsertarVerticeActionPerformed
        // INSERTAR VERTICE
        String verticeTemp = jTextFieldVertice.getText().toUpperCase().trim();
        String mensaje = "ERROR!";
        
        if(!verticeTemp.isBlank()){
            char vertice = verticeTemp.charAt(0);
            boolean respuesta = grafo.insertarVertice(vertice);
            if(respuesta){
                mensaje = "Se inserto el vertice correctamente";
            }
        }
        
        jTextFieldVertice.setText("");
        this.setTitle(mensaje);
    }//GEN-LAST:event_jButtonInsertarVerticeActionPerformed

    private void jButtonEliminarVerticeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEliminarVerticeActionPerformed
        // ELIMINAR VERTICE
        String verticeTemp = jTextFieldVertice.getText().toUpperCase().trim();
        String mensaje = "ERROR!";
        
        if(!verticeTemp.isBlank()){
            char vertice = verticeTemp.charAt(0);
            boolean respuesta = grafo.eliminarVertice(vertice);
            if(respuesta){
                mensaje = "Se elimino el vertice correctamente";
            }
        }
        
        jTextFieldVertice.setText("");
        this.setTitle(mensaje);
    }//GEN-LAST:event_jButtonEliminarVerticeActionPerformed

    private void jButtonInsertarAristaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonInsertarAristaActionPerformed
        // INSERTAR ARISTA
        String origenTemp = jTextFieldOrigen.getText().toUpperCase().trim();
        String DestinoTemp = jTextFieldDestino.getText().toUpperCase().trim();
        String mensaje = "ERROR!";
        
        if(!origenTemp.isBlank() && !DestinoTemp.isBlank()){
            char origen = origenTemp.charAt(0);
            char destino = DestinoTemp.charAt(0);
            boolean respuesta = grafo.insertarArista(origen, destino);
            if(respuesta){
                mensaje = "Se inserto la arista correctamente";
            }
        }
        
        jTextFieldOrigen.setText("");
        jTextFieldDestino.setText("");
        this.setTitle(mensaje);
    }//GEN-LAST:event_jButtonInsertarAristaActionPerformed

    private void jButtonEliminarAristaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEliminarAristaActionPerformed
        // ELIMINAR ARISTA
        String origenTemp = jTextFieldOrigen.getText().toUpperCase().trim();
        String DestinoTemp = jTextFieldDestino.getText().toUpperCase().trim();
        String mensaje = "ERROR!";
        
        if(!origenTemp.isBlank() && !DestinoTemp.isBlank()){
            char origen = origenTemp.charAt(0);
            char destino = DestinoTemp.charAt(0);
            boolean respuesta = grafo.eliminarArista(origen, destino);
            if(respuesta){
                mensaje = "Se elimino la arista correctamente";
            }
        }
        
        jTextFieldOrigen.setText("");
        jTextFieldDestino.setText("");
        this.setTitle(mensaje);
    }//GEN-LAST:event_jButtonEliminarAristaActionPerformed

    private void jButtonMatrizAdyacenciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonMatrizAdyacenciaActionPerformed
        // MATRIZ DE ADYACENCIA
        
        int[][] matriz = grafo.getMatriz();
        
        mostrar(matriz);
    }//GEN-LAST:event_jButtonMatrizAdyacenciaActionPerformed

    private void jButtonListaAdyacenciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonListaAdyacenciaActionPerformed
        // LISTA DE ADYACENCIA
        String verticeTemp = jTextFieldVertice.getText().toUpperCase().trim();
        
        String mensaje = "ERROR!", respuesta = "";
        if(!verticeTemp.isBlank()){
            char vertice = verticeTemp.charAt(0);
            respuesta = grafo.getListaAdyacencia(vertice); 
            if(!respuesta.isBlank()){
               mensaje = "Se genero la lista correctamente";
               jTextArea1.setText(respuesta);
            }
        }
        
        jTextFieldVertice.setText("");
        this.setTitle(mensaje);
        jTextArea1.setText(respuesta);
    }//GEN-LAST:event_jButtonListaAdyacenciaActionPerformed

    private void jButtonVerificarCaminoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonVerificarCaminoActionPerformed
        // VERIFICAR CAMINO
        String pathTemp = jTextFieldPATH.getText().trim().toUpperCase();
        String mensaje = "ERROR!";
        
        if(!pathTemp.isBlank()){
            String path = pathTemp;
            boolean respuesta = grafo.getVerificarCamino(path);
            if(respuesta){
                mensaje = "EL CAMINO EXISTE";
            }
        }
        
        jTextFieldVertice.setText("");
        this.setTitle(mensaje);
    }//GEN-LAST:event_jButtonVerificarCaminoActionPerformed
   
    public void mostrar(int[][] matriz){
        String cad = "";
        for (int i = 0; i < matriz.length; i++) {
            for (int j = 0; j < matriz.length; j++) {
                cad += matriz[i][j];
            }
            cad += "\n";
        }
        jTextArea1.setText(cad);
    }
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ventana().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonEliminarArista;
    private javax.swing.JButton jButtonEliminarVertice;
    private javax.swing.JButton jButtonInsertarArista;
    private javax.swing.JButton jButtonInsertarVertice;
    private javax.swing.JButton jButtonListaAdyacencia;
    private javax.swing.JButton jButtonMatrizAdyacencia;
    private javax.swing.JButton jButtonVerificarCamino;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextArea jTextArea2;
    private javax.swing.JTextField jTextFieldDestino;
    private javax.swing.JTextField jTextFieldOrigen;
    private javax.swing.JTextField jTextFieldPATH;
    private javax.swing.JTextField jTextFieldVertice;
    // End of variables declaration//GEN-END:variables
}
